Project = yppoll
Install_Dir = /usr/sbin

CFILES = yppoll.c
MANPAGES = yppoll.8

Extra_CC_Flags = -Wall -Werror -fPIE
Extra_LD_Flags = -dead_strip -pie

include $(MAKEFILEPATH)/CoreOS/ReleaseControl/BSDCommon.make
