Project = ypmatch
Install_Dir = /usr/bin

CFILES = ypmatch.c
MANPAGES = ypmatch.1

Extra_CC_Flags = -Wall -Werror -fPIE
Extra_LD_Flags = -dead_strip -pie

include $(MAKEFILEPATH)/CoreOS/ReleaseControl/BSDCommon.make
