Project = stdethers
Install_Dir = /usr/sbin

CFILES = stdethers.c
MANPAGES = stdethers.8

Extra_CC_Flags = -Wall -Werror -mdynamic-no-pic
Extra_LD_Flags = -dead_strip

include $(MAKEFILEPATH)/CoreOS/ReleaseControl/BSDCommon.make
