Project = stdhosts
Install_Dir = /usr/sbin

CFILES = stdhosts.c
MANPAGES = stdhosts.8

Extra_CC_Flags = -Wall -Werror -mdynamic-no-pic
Extra_LD_Flags = -dead_strip

include $(MAKEFILEPATH)/CoreOS/ReleaseControl/BSDCommon.make
